#include "gestionFS.h"

#define devel 1

void manuel(void);

int main(int argc,char** argv){
    //L est la machine lua principale
    lua_State* L;
    L = luaL_newstate();
    luaL_openlibs(L);
    gFS_include(L);

    //On charge les fichiers
#if devel == 1
    fprintf(stdout,"Mode de developpement...\n");
    luaL_dofile(L,"TexClean.lua"); //dev
#else
    luaL_dofile(L,"/usr/local/share/texclean/TexClean.luac");
#endif
    
    lua_getglobal(L,"clean");
    if(argc == 2 && !strcmp(*(argv+1),"all")){ //On efface les pdf du dossier courant
        lua_pushstring(L,".");
        lua_pushboolean(L,1);
    }else if(argc == 1 || (argc == 2 && !strcmp(*(argv+1),"limited"))){ //On efface tout sauf les résultats du dossier courant
        lua_pushstring(L,".");
        lua_pushboolean(L,0);
    }else if((argc==2 && gFS_isDir(*(argv+1))) || (argc==3 && !strcmp(*(argv+1),"limited") && gFS_isDir(*(argv+2)) )){ //On efface tout sauf les résultats du dossier en argument
        lua_pushstring(L,*(argv+1));
        lua_pushboolean(L,0);
    }else if(argc == 3 && !strcmp(*(argv+1),"all") && gFS_isDir(*(argv+2))){
        lua_pushstring(L,*(argv+2));
        lua_pushboolean(L,1);
    }else{
        manuel();
        lua_close(L);
        return 1;
    }
    lua_call(L,2,0);
    lua_close(L);
    return 0;
}

void manuel(void){
    fprintf(stderr,"This software is used to clean files ccreated by LaTeX compilation.\n    Usage: texcleanplus <option> <directory>\n    Available option:\n        all : remove all files generated by LaTeX compilation including .ps and .pdf files\n        limited (default) : keep .ps and .pdf\n\n    ");
}

