#include "gestionFS.h"

#define devel 1

void manuel(void);

int main(int argc,char** argv){
    //L est la machine lua principale
    lua_State* L;
    L = luaL_newstate();
    luaL_openlibs(L);
    gFS_include(L);

    //On charge les fichiers
#if devel == 1
    fprintf(stdout,"Mode de developpement...\n");
    luaL_dofile(L,"TexClean.lua"); //dev
#else
    luaL_dofile(L,"/usr/local/share/texclean/TexClean.luac");
#endif
    
    lua_getglobal(L,"clean");
    if(argc == 2 && !strcmp(*(argv+1),"all")){ //On efface les pdf
        lua_pushboolean(L,1);
    }else if(argc == 1){
        lua_pushboolean(L,0);
    }else{
        manuel();
        lua_close(L);
        return 1;
    }
    lua_call(L,1,0);
    lua_close(L);
    return 0;
}

void manuel(void){
    fprintf(stderr,"This software is used to clean files ccreated by LaTeX compilation.\n    Usage: texcleanplus <option>\n    Available option:\n        all : remove all files generated by LaTeX compilation including .ps and .pdf files\n        \" \" (default) : keep .ps and .pdf");
}

